In [1]:
import os
import zipfile

raw_dir = r"C:\Users\avari\data\raw"

zip_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.zip")

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(raw_dir)

os.listdir(raw_dir)

['coconut_csv_lite-05-2026.csv', 'coconut_csv_lite-05-2026.zip']

In [2]:
import pandas as pd

csv_files = [f for f in os.listdir(raw_dir) if f.endswith(".csv")]
csv_files

['coconut_csv_lite-05-2026.csv']

In [3]:
csv_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.csv")
df = pd.read_csv(csv_path)

df.columns.tolist()
df.head()

C:\Users\avari\AppData\Local\Temp\ipykernel_27384\42737912.py:2: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

,id,identifier,canonical_smiles,standard_inchi,standard_inchi_key,name,iupac_name,annotation_level,total_atom_count,heavy_atom_count,...,murcko_framework,np_likeness,chemical_class,chemical_sub_class,chemical_super_class,direct_parent_classification,np_classifier_pathway,np_classifier_superclass,np_classifier_class,np_classifier_is_glycoside
0,283639,CNP0186424.2,CO[C@@H]1C=C[C@]2(C3=CC4=C(C=C3CO)OCO4)[C@H](C...,InChI=1S/C18H23NO5/c1-19-8-17(21)18(4-3-12(22-...,XEEPVFFWNATEGX-IEGACIPQSA-N,NaN,"(3~{R},3~{a}~{S},6~{S},7~{a}~{S})-3~{a}-[6-(hy...",4,47,24,...,O1c2ccc(cc2OC1)C34C=CCCC4NCC3,2.15,Benzodioxoles,Benzodioxoles,Organoheterocyclic compounds,Benzodioxoles,Alkaloids,Tyrosine alkaloids,Amarylidaceae alkaloids,False
1,1076780,CNP0092620.2,CC(=O)OC1=CC(CO)=C2C(=O)C3=C(O)C(CC4=CC=CC(CO)...,"InChI=1S/C48H54N4O15/c1-24-44(61)48(62,63)45(6...",XKQGTIKVTZUZMV-ROUUEPNLSA-N,NaN,[1-[(~{E})-2-[3-[(2~{R})-5-amino-2-hydroxy-pen...,1,121,67,...,O(c1cc2c(cc1Cc3ccccc3)Cc4cccc(C=Cc5ccccc5)c4C2...,1.74,Anthracenes,Anthraquinones,Benzenoids,Anthraquinones,NaN,NaN,NaN,True
2,865804,CNP0150317.4,CC1=C(Cl)C=CC2=C1NC(=O)[C@]21N[C@@H]([C@@H](C)...,InChI=1S/C24H22ClN3O6/c1-10-14(25)5-4-13-19(10...,BWMVPJNRGUQRFV-QZICXMLHSA-N,NaN,"(1~{R},3~{R},3~{a}~{R},6~{a}~{S})-5-(1,3-benzo...",1,56,34,...,O1c2ccc(cc2OC1)CN3CC4CNC5(c6ccccc6NC5)C4C3,-0.40,Carboxylic acids and derivatives,"Amino acids, peptides, and analogues",Organic acids and derivatives,Alpha amino acids,Alkaloids,NaN,NaN,False
3,1076811,CNP0092395.1,CCC[C@@H]1C/C=C2/OC(=O)[C@@]34C5=C(CC[C@@]23[C...,InChI=1S/C47H59N3O4/c1-4-8-32-14-18-39-45-20-1...,SZFHNPGGVXQHRI-SVFGHVILSA-N,"(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...","(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...",1,113,54,...,O1C2=CCCN3CC4CN5C6=C(C=CC5C(C3)C4)CCC7CCC8=C(C...,2.00,Quinolizines,Quinolizines,Organoheterocyclic compounds,Quinolizines,Alkaloids,NaN,NaN,False
4,865833,CNP0268019.16,C[C@@H]1O[C@@H](O[C@@H]2[C@@H](OC3=CC(O)=C4C(=...,InChI=1S/C27H32O14/c1-10-20(32)22(34)24(36)26(...,DFPMSGMNTNDNHN-MAJQQVGWSA-N,"(2S)-7-[(2R,3S,4S,5S,6S)-4,5-dihydroxy-6-(hydr...","(2~{S})-7-[(2~{R},3~{S},4~{S},5~{S},6~{S})-4,5...",1,73,41,...,O(c1ccc2c(OC(c3ccccc3)CC2)c1)C4OCCCC4OC5OCCCC5,2.25,Flavonoids,Flavonoid glycosides,Phenylpropanoids and polyketides,Flavonoid-7-O-glycosides,Shikimates and Phenylpropanoids,Flavonoids,Flavanones,True

In [4]:
csv_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.csv")
df = pd.read_csv(csv_path)

df.columns.tolist()
df.head()

C:\Users\avari\AppData\Local\Temp\ipykernel_27384\42737912.py:2: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_path)

,id,identifier,canonical_smiles,standard_inchi,standard_inchi_key,name,iupac_name,annotation_level,total_atom_count,heavy_atom_count,...,murcko_framework,np_likeness,chemical_class,chemical_sub_class,chemical_super_class,direct_parent_classification,np_classifier_pathway,np_classifier_superclass,np_classifier_class,np_classifier_is_glycoside
0,283639,CNP0186424.2,CO[C@@H]1C=C[C@]2(C3=CC4=C(C=C3CO)OCO4)[C@H](C...,InChI=1S/C18H23NO5/c1-19-8-17(21)18(4-3-12(22-...,XEEPVFFWNATEGX-IEGACIPQSA-N,NaN,"(3~{R},3~{a}~{S},6~{S},7~{a}~{S})-3~{a}-[6-(hy...",4,47,24,...,O1c2ccc(cc2OC1)C34C=CCCC4NCC3,2.15,Benzodioxoles,Benzodioxoles,Organoheterocyclic compounds,Benzodioxoles,Alkaloids,Tyrosine alkaloids,Amarylidaceae alkaloids,False
1,1076780,CNP0092620.2,CC(=O)OC1=CC(CO)=C2C(=O)C3=C(O)C(CC4=CC=CC(CO)...,"InChI=1S/C48H54N4O15/c1-24-44(61)48(62,63)45(6...",XKQGTIKVTZUZMV-ROUUEPNLSA-N,NaN,[1-[(~{E})-2-[3-[(2~{R})-5-amino-2-hydroxy-pen...,1,121,67,...,O(c1cc2c(cc1Cc3ccccc3)Cc4cccc(C=Cc5ccccc5)c4C2...,1.74,Anthracenes,Anthraquinones,Benzenoids,Anthraquinones,NaN,NaN,NaN,True
2,865804,CNP0150317.4,CC1=C(Cl)C=CC2=C1NC(=O)[C@]21N[C@@H]([C@@H](C)...,InChI=1S/C24H22ClN3O6/c1-10-14(25)5-4-13-19(10...,BWMVPJNRGUQRFV-QZICXMLHSA-N,NaN,"(1~{R},3~{R},3~{a}~{R},6~{a}~{S})-5-(1,3-benzo...",1,56,34,...,O1c2ccc(cc2OC1)CN3CC4CNC5(c6ccccc6NC5)C4C3,-0.40,Carboxylic acids and derivatives,"Amino acids, peptides, and analogues",Organic acids and derivatives,Alpha amino acids,Alkaloids,NaN,NaN,False
3,1076811,CNP0092395.1,CCC[C@@H]1C/C=C2/OC(=O)[C@@]34C5=C(CC[C@@]23[C...,InChI=1S/C47H59N3O4/c1-4-8-32-14-18-39-45-20-1...,SZFHNPGGVXQHRI-SVFGHVILSA-N,"(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...","(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...",1,113,54,...,O1C2=CCCN3CC4CN5C6=C(C=CC5C(C3)C4)CCC7CCC8=C(C...,2.00,Quinolizines,Quinolizines,Organoheterocyclic compounds,Quinolizines,Alkaloids,NaN,NaN,False
4,865833,CNP0268019.16,C[C@@H]1O[C@@H](O[C@@H]2[C@@H](OC3=CC(O)=C4C(=...,InChI=1S/C27H32O14/c1-10-20(32)22(34)24(36)26(...,DFPMSGMNTNDNHN-MAJQQVGWSA-N,"(2S)-7-[(2R,3S,4S,5S,6S)-4,5-dihydroxy-6-(hydr...","(2~{S})-7-[(2~{R},3~{S},4~{S},5~{S},6~{S})-4,5...",1,73,41,...,O(c1ccc2c(OC(c3ccccc3)CC2)c1)C4OCCCC4OC5OCCCC5,2.25,Flavonoids,Flavonoid glycosides,Phenylpropanoids and polyketides,Flavonoid-7-O-glycosides,Shikimates and Phenylpropanoids,Flavonoids,Flavanones,True

In [6]:
import pandas as pd

csv_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.csv")
df = pd.read_csv(csv_path, low_memory=False)

print(df.columns.tolist())
df.head()

['id', 'identifier', 'canonical_smiles', 'standard_inchi', 'standard_inchi_key', 'name', 'iupac_name', 'annotation_level', 'total_atom_count', 'heavy_atom_count', 'molecular_weight', 'exact_molecular_weight', 'molecular_formula', 'alogp', 'topological_polar_surface_area', 'rotatable_bond_count', 'hydrogen_bond_acceptors', 'hydrogen_bond_donors', 'hydrogen_bond_acceptors_lipinski', 'hydrogen_bond_donors_lipinski', 'lipinski_rule_of_five_violations', 'aromatic_rings_count', 'qed_drug_likeliness', 'formal_charge', 'fractioncsp3', 'number_of_minimal_rings', 'van_der_walls_volume', 'contains_sugar', 'contains_ring_sugars', 'contains_linear_sugars', 'murcko_framework', 'np_likeness', 'chemical_class', 'chemical_sub_class', 'chemical_super_class', 'direct_parent_classification', 'np_classifier_pathway', 'np_classifier_superclass', 'np_classifier_class', 'np_classifier_is_glycoside']

,id,identifier,canonical_smiles,standard_inchi,standard_inchi_key,name,iupac_name,annotation_level,total_atom_count,heavy_atom_count,...,murcko_framework,np_likeness,chemical_class,chemical_sub_class,chemical_super_class,direct_parent_classification,np_classifier_pathway,np_classifier_superclass,np_classifier_class,np_classifier_is_glycoside
0,283639,CNP0186424.2,CO[C@@H]1C=C[C@]2(C3=CC4=C(C=C3CO)OCO4)[C@H](C...,InChI=1S/C18H23NO5/c1-19-8-17(21)18(4-3-12(22-...,XEEPVFFWNATEGX-IEGACIPQSA-N,NaN,"(3~{R},3~{a}~{S},6~{S},7~{a}~{S})-3~{a}-[6-(hy...",4,47,24,...,O1c2ccc(cc2OC1)C34C=CCCC4NCC3,2.15,Benzodioxoles,Benzodioxoles,Organoheterocyclic compounds,Benzodioxoles,Alkaloids,Tyrosine alkaloids,Amarylidaceae alkaloids,False
1,1076780,CNP0092620.2,CC(=O)OC1=CC(CO)=C2C(=O)C3=C(O)C(CC4=CC=CC(CO)...,"InChI=1S/C48H54N4O15/c1-24-44(61)48(62,63)45(6...",XKQGTIKVTZUZMV-ROUUEPNLSA-N,NaN,[1-[(~{E})-2-[3-[(2~{R})-5-amino-2-hydroxy-pen...,1,121,67,...,O(c1cc2c(cc1Cc3ccccc3)Cc4cccc(C=Cc5ccccc5)c4C2...,1.74,Anthracenes,Anthraquinones,Benzenoids,Anthraquinones,NaN,NaN,NaN,True
2,865804,CNP0150317.4,CC1=C(Cl)C=CC2=C1NC(=O)[C@]21N[C@@H]([C@@H](C)...,InChI=1S/C24H22ClN3O6/c1-10-14(25)5-4-13-19(10...,BWMVPJNRGUQRFV-QZICXMLHSA-N,NaN,"(1~{R},3~{R},3~{a}~{R},6~{a}~{S})-5-(1,3-benzo...",1,56,34,...,O1c2ccc(cc2OC1)CN3CC4CNC5(c6ccccc6NC5)C4C3,-0.40,Carboxylic acids and derivatives,"Amino acids, peptides, and analogues",Organic acids and derivatives,Alpha amino acids,Alkaloids,NaN,NaN,False
3,1076811,CNP0092395.1,CCC[C@@H]1C/C=C2/OC(=O)[C@@]34C5=C(CC[C@@]23[C...,InChI=1S/C47H59N3O4/c1-4-8-32-14-18-39-45-20-1...,SZFHNPGGVXQHRI-SVFGHVILSA-N,"(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...","(5~{S},7~{S},8~{R},10~{E},14~{S},15~{S},16~{S}...",1,113,54,...,O1C2=CCCN3CC4CN5C6=C(C=CC5C(C3)C4)CCC7CCC8=C(C...,2.00,Quinolizines,Quinolizines,Organoheterocyclic compounds,Quinolizines,Alkaloids,NaN,NaN,False
4,865833,CNP0268019.16,C[C@@H]1O[C@@H](O[C@@H]2[C@@H](OC3=CC(O)=C4C(=...,InChI=1S/C27H32O14/c1-10-20(32)22(34)24(36)26(...,DFPMSGMNTNDNHN-MAJQQVGWSA-N,"(2S)-7-[(2R,3S,4S,5S,6S)-4,5-dihydroxy-6-(hydr...","(2~{S})-7-[(2~{R},3~{S},4~{S},5~{S},6~{S})-4,5...",1,73,41,...,O(c1ccc2c(OC(c3ccccc3)CC2)c1)C4OCCCC4OC5OCCCC5,2.25,Flavonoids,Flavonoid glycosides,Phenylpropanoids and polyketides,Flavonoid-7-O-glycosides,Shikimates and Phenylpropanoids,Flavonoids,Flavanones,True

In [7]:
import os

base_dir = r"C:\Users\avari"
raw_dir = os.path.join(base_dir, "data", "raw")
processed_dir = os.path.join(base_dir, "data", "processed")
results_dir = os.path.join(base_dir, "data", "results")

os.makedirs(processed_dir, exist_ok=True)
os.makedirs(results_dir, exist_ok=True)

raw_dir, processed_dir, results_dir

('C:\\Users\\avari\\data\\raw',
 'C:\\Users\\avari\\data\\processed',
 'C:\\Users\\avari\\data\\results')

In [8]:
import os
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors
import matplotlib.pyplot as plt
import seaborn as sns

base_dir = r"C:\Users\avari"
raw_dir = os.path.join(base_dir, "data", "raw")
processed_dir = os.path.join(base_dir, "data", "processed")
results_dir = os.path.join(base_dir, "data", "results")

csv_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.csv")
df = pd.read_csv(csv_path, low_memory=False)

subset = df.sample(n=2000, random_state=42).copy()

smiles_col = "canonical_smiles"

subset["mol"] = subset[smiles_col].apply(
    lambda x: Chem.MolFromSmiles(str(x)) if pd.notnull(x) else None
)

clean = subset[subset["mol"].notnull()].copy()

print("Subset size:", len(subset))
print("Valid molecules:", len(clean))

def calc_desc(mol):
    return {
        "MolWt_rdkit": Descriptors.MolWt(mol),
        "LogP_rdkit": Descriptors.MolLogP(mol),
        "TPSA_rdkit": Descriptors.TPSA(mol),
        "HDonors_rdkit": Descriptors.NumHDonors(mol),
        "HAcceptors_rdkit": Descriptors.NumHAcceptors(mol),
        "RotBonds_rdkit": Descriptors.NumRotatableBonds(mol),
    }

desc_df = clean["mol"].apply(calc_desc).apply(pd.Series)

clean = pd.concat([clean.reset_index(drop=True), desc_df.reset_index(drop=True)], axis=1)

clean_path = os.path.join(processed_dir, "coconut_subset_cleaned.csv")
clean.to_csv(clean_path, index=False)
clean_path

ModuleNotFoundError: No module named 'rdkit'

In [1]:
from rdkit import Chem
from rdkit.Chem import Descriptors

Chem.MolFromSmiles("CCO")

AttributeError: module 'rdkit.Chem.Draw.rdMolDraw2D' has no attribute 'MolDraw2DCairo'

In [2]:
from rdkit import Chem
from rdkit.Chem import Descriptors

mol = Chem.MolFromSmiles("CCO")
print(mol is not None)
print(Descriptors.MolWt(mol))

True
46.069

In [3]:
import os
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors
import matplotlib.pyplot as plt
import seaborn as sns

base_dir = r"C:\Users\avari"
raw_dir = os.path.join(base_dir, "data", "raw")
processed_dir = os.path.join(base_dir, "data", "processed")
results_dir = os.path.join(base_dir, "data", "results")

os.makedirs(processed_dir, exist_ok=True)
os.makedirs(results_dir, exist_ok=True)

csv_path = os.path.join(raw_dir, "coconut_csv_lite-05-2026.csv")
df = pd.read_csv(csv_path, low_memory=False)

subset = df.sample(n=2000, random_state=42).copy()

smiles_col = "canonical_smiles"

subset["mol"] = subset[smiles_col].apply(
    lambda x: Chem.MolFromSmiles(str(x)) if pd.notnull(x) else None
)

clean = subset[subset["mol"].notnull()].copy()

print("Subset size:", len(subset))
print("Valid molecules:", len(clean))

def calc_desc(mol):
    return {
        "MolWt_rdkit": Descriptors.MolWt(mol),
        "LogP_rdkit": Descriptors.MolLogP(mol),
        "TPSA_rdkit": Descriptors.TPSA(mol),
        "HDonors_rdkit": Descriptors.NumHDonors(mol),
        "HAcceptors_rdkit": Descriptors.NumHAcceptors(mol),
        "RotBonds_rdkit": Descriptors.NumRotatableBonds(mol),
    }

desc_df = clean["mol"].apply(calc_desc).apply(pd.Series)

clean = pd.concat([clean.reset_index(drop=True), desc_df.reset_index(drop=True)], axis=1)

clean_path = os.path.join(processed_dir, "coconut_subset_cleaned.csv")
clean.to_csv(clean_path, index=False)
clean_path

Subset size: 2000
Valid molecules: 2000

'C:\\Users\\avari\\data\\processed\\coconut_subset_cleaned.csv'

In [4]:
desc_cols = [
    "molecular_weight",
    "alogp",
    "topological_polar_surface_area",
    "hydrogen_bond_donors",
    "hydrogen_bond_acceptors",
    "MolWt_rdkit",
    "LogP_rdkit",
    "TPSA_rdkit",
    "HDonors_rdkit",
    "HAcceptors_rdkit",
    "RotBonds_rdkit",
]

descriptor_table = clean[desc_cols].copy()
desc_path = os.path.join(processed_dir, "descriptor_table.csv")
descriptor_table.to_csv(desc_path, index=False)
desc_path

'C:\\Users\\avari\\data\\processed\\descriptor_table.csv'

In [5]:
sns.set(style="whitegrid")

plt.figure(figsize=(6,4))
sns.histplot(clean["MolWt_rdkit"], bins=40)
plt.xlabel("Molecular weight (RDKit)")
plt.title("Natural-product molecular weight distribution")
plt.tight_layout()
plt.savefig(os.path.join(results_dir, "molwt_hist.png"), dpi=300)
plt.close()

plt.figure(figsize=(6,4))
sns.histplot(clean["LogP_rdkit"], bins=40)
plt.xlabel("LogP (RDKit)")
plt.title("Natural-product LogP distribution")
plt.tight_layout()
plt.savefig(os.path.join(results_dir, "logp_hist.png"), dpi=300)
plt.close()

plt.figure(figsize=(6,4))
sns.scatterplot(data=clean, x="MolWt_rdkit", y="LogP_rdkit", alpha=0.5)
plt.xlabel("Molecular weight (RDKit)")
plt.ylabel("LogP (RDKit)")
plt.title("MW vs LogP for COCONUT subset")
plt.tight_layout()
plt.savefig(os.path.join(results_dir, "mw_vs_logp.png"), dpi=300)
plt.close()

plt.figure(figsize=(6,5))
corr_cols = ["MolWt_rdkit", "LogP_rdkit", "TPSA_rdkit", "HDonors_rdkit", "HAcceptors_rdkit", "RotBonds_rdkit"]
corr = clean[corr_cols].corr()
sns.heatmap(corr, annot=True, cmap="viridis")
plt.title("Descriptor correlation heatmap")
plt.tight_layout()
plt.savefig(os.path.join(results_dir, "descriptor_heatmap.png"), dpi=300)
plt.close()

In [6]:
import os

base_dir = r"C:\Users\avari"
results_dir = os.path.join(base_dir, "data", "results")
os.listdir(results_dir)

['descriptor_heatmap.png', 'logp_hist.png', 'molwt_hist.png', 'mw_vs_logp.png']